# Taps
tap 'homebrew/cask'
tap "homebrew/cask-fonts"
tap 'homebrew/bundle'

# Formulae
brew "exa"
brew "fzf"
brew "starship"
brew "thefuck"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-you-should-use"
brew "zoxide"

# Apps
cask 'alacritty'
cask "font-hack-nerd-font"
