# Taps
tap 'homebrew/cask'
tap "homebrew/cask-fonts"
tap 'homebrew/bundle'

# Formulae
brew "thefuck"
brew "starship"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zoxide"

# Apps
cask 'alacritty'
cask "font-hack-nerd-font"
