#!/bin/sh

# Dotfiles git bare $HOME dir as config
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# Navigation
alias q="cd ~"            # Go home
alias -- -="cd -"         # Go back
alias dl="cd ~/Downloads" # Go to Downloads
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

# Clear
alias c="clear"
alias clr="clear"
alias ckear="clear"

# History
alias h="history"

# List commands
alias l="ls"
alias l='ls -lAh'
alias ls="ls -a"
alias la="ls -a"
alias ll="ls -al"

# Copy output of last command
alias clo='"$(history | tail -2 | sed "s/  [0-9]*  //;2d")" > /tmp/cmdoutput && cat /tmp/cmdoutput | xsel -b && notify-send "Terminal" "Ouput Copied"'

# Confirm before changing things
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -I --preserve-root'

# Enhanced grep
alias grep='grep --color=auto'
