#!/bin/sh

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'Brewfile'; then
  echo
  echo "📦 Brewfile changed. Do you want to run install now? [y/N]: "

	read -r REPLY

	case "$REPLY" in
	y | Y)
    brew bundle install --file="$HOME/.scripts/Brewfile"

		;;
	*)
		echo "To install later, run:"
		echo
    echo "> brew bundle install --file=\"$HOME/.scripts/Brewfile\""
		echo

		exit
		;;
	esac
fi
