#!/usr/bin/env bash

function set_user() {
	# The file names are hardcoded as imports in the git config file.
	if [[ "$1" != "global" ]] && [[ "$1" != "dotfiles" ]]; then
		echo "Only 'global' and 'dotfiles' are valid options for git user setup."
		return 0
	fi

	if gum confirm "Do you want to setup a '$1' git user?"; then
		NAME=$(gum input --prompt "Name: ")
		EMAIL=$(gum input --prompt "Email: ")

		gum confirm "Confirm setting '$1' config user '$NAME <$EMAIL>'?"

		if [[ "$1" == "dotfiles" ]]; then
			yadm gitconfig "user.name" "$NAME"
			yadm gitconfig "user.email" "$EMAIL"
		else
			file_path="$XDG_CONFIG_HOME/git/custom_$1"

			rm -rf "$file_path"
			touch "$file_path"

			git config --file="$file_path" user.name "$NAME"
			git config --file="$file_path" user.email "$EMAIL"
		fi
	fi
}

set_user global
set_user dotfiles
