#!/bin/bash

# Heavily based on Mathias Bynens' macOS script (But with some gum):
# https://github.com/mathiasbynens/dotfiles/blob/master/.macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `macos` has finished
while true; do
	sudo -n true
	sleep 60
	kill -0 "$$" || exit
done 2>/dev/null &

###############################################################################
# Computer Name                                                               #
###############################################################################

comp_curr_name=$(scutil --get ComputerName)

set_computer_name() {
	new="${1:-$comp_curr_name}"

	if [[ "$new" != "$comp_curr_name" ]]; then
		sudo scutil --set ComputerName "$new"

		sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$new"

		gum log --structured --level info "The computer name was changed to '$new'"
	else
		gum log --structured --level warn "The computer name was not changed"
	fi
}

gum confirm "Set computer name? (Current: $comp_curr_name)" &&
	set_computer_name "$(gum input --prompt "Computer Name: ")"
