#!/bin/sh

# Navigation
alias q="cd ~"            # Go home
alias -- -="cd -"         # Go back
alias dl="cd ~/Downloads" # Go to Downloads
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

# Clear
alias c="clear"
alias clr="clear"
alias ckear="clear"

# List commands
alias ls='exa --icons -l -h -m --group-directories-first'
alias la='ls -a'
alias l="la"

# Copy output of last command
alias clo='"$(history | tail -2 | sed "s/  [0-9]*  //;2d")" > /tmp/cmdoutput && cat /tmp/cmdoutput | xsel -b && notify-send "Terminal" "Ouput Copied"'

# Confirm before changing things
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -I'

# Enhanced grep
alias grep='grep --color=auto'

# Enhanced cat
alias cat=bat

# Neovim
alias vim=nvim
alias vi=nvim

############
# Homebrew #
############

alias hbs="brew search"
alias hbi="brew install"
alias hbl="brew list"
alias hbu="brew uninstall"
alias hbn="brew info"
